### ISSUE TITLE
eslint v4 support

### ISSUE THREAD

**Issue by thrucker** [actano/javascript#2]
This is currently blocked by missing eslint v4 support in upstream airbnb/javascript. See airbnb/javascript#1447.

**Comment by hpurmann** [comment]
They [released version0 `15.1.0`](https://github.com/airbnb/javascript/issues/1447#issuecomment-317335861) now.

**Comment by thrucker** [comment]
See https://github.com/actano/javascript/commit/fe5d17aaa82be196f4b83304697e32bfd7d9cf24.
Forgot to close this one though. ;)
